### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#1]
Can you add English language?

**Comment by wwwwwwzx** [comment]
A new version was released.
Since it's beta version, there are some unknown game mechanics needs to figure out.
You needs to manually try the "Frame Correction" to get the correct IV spreads.

**Comment by Real96** [comment]
Translation is great! Thanks a lot!

Another little requet: why don't you add a language selector in the main branche? In that way both English and Chinese version would be updated at the same time

**Comment by wwwwwwzx** [comment]
Well, I was just playing around with GitHub. Now they are merged.

**Comment by Real96** [comment]
Thanks a lot! Great translation! :)
