### ISSUE TITLE
UBs mode doesn't find all the possible UBs spreads

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#11]
This is a Guzzlord Rng i made 3 days ago: http://i.imgur.com/ZaUcsPP.png
This is the spread (the second one): http://i.imgur.com/7Ykvmel.png (there is the X under `UB?` column)
But if i search it today with Guzzlord mode (UB rate 15) i can't find it: http://i.imgur.com/cRWWYkI.png
If i put Guzzlord mode with UB rate 35 instead, i find it: http://i.imgur.com/LQ4uNa8.png

Just made another test. These are the results:
Spread UB Rate 34: http://i.imgur.com/NdA1LeZ.png
RNGed Guzzlord: http://i.imgur.com/BEbQsL5.png

**Comment by wwwwwwzx** [comment]
It seems that UB Rate needs to be carefully tested now, use the ub value in `UB? `Column with `Advanced `Checked, do threshold test for each UB

**Comment by Real96** [comment]
Tell me if i can test something  in particular

**Comment by wwwwwwzx** [comment]
I guess Tapus Sync Problem were fixed. Use `FrameCorrection = 5` on the left. And it seems that for tapu fini is 100% correct, koko/lele/bulu will be within 2 frames (0, +1)

**Comment by Real96** [comment]
Yes, tapus 100% correct sync :D fini 5, i need to find the other 3

**Comment by wwwwwwzx** [comment]
Ok after several rounds of test, it should be confirmed the sync problem is solved, frame correction can be 5 or 6 based on the timing when you are at. I guess it's better to fix at 5 and we can see both. I would like to say for multiply NPCs case (Solgaleo Lunala) the results could be worse. (I don't have any available save for test unfortunately.)

**Comment by Real96** [comment]
I can give you my saves file, i've got all stationary ready. Anyway for fini is 5-6, so don't know if 5 fixed would be good.

**Comment by Real96** [comment]
God i closed it, can you re-open?

**Comment by wwwwwwzx** [comment]
If you choose 5, and you can see tapu fini will be within {0 +2} (+1? ), 5 or 6 is just a shift and doesn't affect sync results

**Comment by wwwwwwzx** [comment]
If you can give me the save file that would be great. Can you send to me by creating a gist?

**Comment by Real96** [comment]
I will make some testa later and let you know. Can i pass you my save files for solgaleo, lunala cosmog?

**Comment by wwwwwwzx** [comment]
Sure I appreciate it

**Comment by Real96** [comment]
I'll come back home in a 2 hours and i'll pass it to you. Is there a way to send you a private message? I don't want to share it pubblicily

**Comment by wwwwwwzx** [comment]
Try wwwwwwzx@gmail.com

**Comment by Real96** [comment]
Fantastic. Wait for them

**Comment by wwwwwwzx** [comment]
UB Rate of Nihilego = 30 confirmed.

**Comment by wwwwwwzx** [comment]
It seems that UB rate at Diglett's Tunnel is over 50, that's a good location. (30 was tested at Wela Volcano Park).

**Comment by Real96** [comment]
Fantastic! The higher is the rate, the higher is the number of the spreads that can be found! I will test all of them

**Comment by wwwwwwzx** [comment]
It's 80! I will move on after catching it..

**Comment by Real96** [comment]
So, for example, if i got Pheromosa with UB rate 85, all the rate under 85 would be a good encounter for it?

**Comment by wwwwwwzx** [comment]
Yes, that means 85% out of the Pokemon you encounter will be Pheromosa

**Comment by Real96** [comment]
Perfect. I'll be home in a bit, and i'll help you test all of the! :) Wela Volcano can't go cover 30?

**Comment by wwwwwwzx** [comment]
I guess so, all value under `UB?` < UB rate should be UB. That's the rule. So you can gradually narrow down the range of the UB rate.

**Comment by Real96** [comment]
That's great. Se will find all of the them really soon

**Comment by wwwwwwzx** [comment]
Thanks a lot!

**Comment by wwwwwwzx** [comment]
FYI, Melemele Meadow = 30

**Comment by Real96** [comment]
I'm testing Resolutin Cave right now

**Comment by Real96** [comment]
Revelation Cave = 80 (that means everything under 79, 80 excluded)

**Comment by wwwwwwzx** [comment]
Nice, that's reasonable.

**Comment by wwwwwwzx** [comment]
And Malie Garden (for Celesteela) =30

**Comment by Real96** [comment]
Perfect. I'm testing Necrozma right now

**Comment by wwwwwwzx** [comment]
And Haina Desert = 30

**Comment by Real96** [comment]
Is it normal that without using honey it is 89 Rate and using honey it can't got over 5?

**Comment by wwwwwwzx** [comment]
The function without using honey are incomplete. Let me try modify a little bit based on my guess.

**Comment by Real96** [comment]
Uh ok. I'm trying rate 6

**Comment by Real96** [comment]
Rate 5 doesn't work. Necrozma is still rate 5 (everything under 4, 5 excluded)

**Comment by wwwwwwzx** [comment]
OK thank you~ It should be 5 from Japanese researcher

**Comment by Real96** [comment]
Yes it is rate 5 but 5 is excluded.

I'm doing the Lush Jungle.

**Comment by wwwwwwzx** [comment]
Yes 5 excluded means alternatives are 0, 1, 2, 3, 4; total five, in percentage=5%. That's the definition of UB rate~

**Comment by Real96** [comment]
Yes, sorry if i repeat always the same things, but i just want to be sure that all the datas that i give to you are clear xD

**Comment by wwwwwwzx** [comment]
No worries, thank you~

**Comment by Real96** [comment]
Xurkitree 23 rate seems to be to higher. I'll try 19

**Comment by Real96** [comment]
Xurkitree rate is 15, 15 exluded. Can you make a try of it? Because i think that's s bit strange

**Comment by wwwwwwzx** [comment]
Sure, after catching Buzzwole. Maybe that's why I choose 15 for default at first

**Comment by Real96** [comment]
Perfect. I'm doing the last one: Verdant Cavern of Pheromosa

**Comment by wwwwwwzx** [comment]
Someone told me it's around 50 for Pheromosa. Go ahead and try~

**Comment by Real96** [comment]
Phemorosa 49 still encounter him. I'll go above. I'm always checking the Sync, it works perfectly, you made a really great job

**Comment by Real96** [comment]
Phemorosa rate is 50 (49 and everything under, 50 excluded)

So these are all i tested: 
Guzzlord 80
Xurkitree 15
Necrozma 5
Phemorosa 50

Pls test again Xurkitree and Necrozma just to be sure, the other are surely correct

**Comment by wwwwwwzx** [comment]
Ok thank you, I will update the data and make a pre-release anyway. Official Stable Release Soon!

**Comment by Real96** [comment]
I'm testing Tapu Fini now. I tell you all the things you asked me today

**Comment by Real96** [comment]
I made some tests. You can fix Tapu Fini frame Correction to 5, if you stop at the frame showed by the app you will hit it 100% of the times. Same thing with the other Tapu. 5 is the magic number for them xD Ans sync works perfectly! After you fix it to 5 i think you can close this issue :) I'm sending the save files to you now

**Comment by wwwwwwzx** [comment]
Thank you, I will look into Cosmog, etc. later. Let me have a rest, XD
