### ISSUE TITLE
Tapu Fini Error when i try to search a spread

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#12]
This is what i get after i click Search:

Le informazioni su come richiamare il debug JIT (Just-In-Time) anziché questa finestra
sono riportate in fondo al messaggio.

************** Testo dell'eccezione **************
System.IndexOutOfRangeException: Indice oltre i limiti della matrice.
   in SMEncounterRNGTool.RNGSearch.time_elapse()
   in SMEncounterRNGTool.RNGSearch.blink_process(Int32 t_total)
   in SMEncounterRNGTool.RNGSearch.Generate(Int32 init)
   in SMEncounterRNGTool.Form1.StationarySearch()
   in SMEncounterRNGTool.Form1.CalcList_Click(Object sender, EventArgs e)
   in System.Windows.Forms.Control.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnClick(EventArgs e)
   in System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.ButtonBase.WndProc(Message& m)
   in System.Windows.Forms.Button.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assembly caricati **************
mscorlib
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SMEncounterRNGTool
    Versione assembly: 1.0.0.0
    Versione Win32: 1.0.0.0
    Base di codice: file:///C:/Users/Fede/Desktop/SMEncounterRNGTool/SMEncounterRNGTool.exe
----------------------------------------
System.Core
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_it_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Accessibility
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
mscorlib.resources
    Versione assembly: 4.0.0.0
    Versione Win32: 4.6.1586.0 built by: NETFXREL2
    Base di codice: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_it_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** Debug JIT **************
Per abilitare il debug JIT, è necessario impostare il valore
jitDebugging nella sezione system.windows.forms del file di configurazione
dell'applicazione o del computer (machine.config).
L'applicazione inoltre deve essere compilata con il debug
abilitato.

Ad esempio:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Quando il debug JIT è abilitato, tutte le eccezioni non gestite
vengono inviate al debugger JIT registrato nel computer,
anziché essere gestite da questa finestra di dialogo.

**Comment by Real96** [comment]
After closing and reopening this error is not appearing anymore, i signaled it because i got it before.

**Comment by wwwwwwzx** [comment]
I don't know where the problem is at. 
Anyway let's talk about Solgaleo & Lunala. They are 50% predictable. It's hard to get perfect results since the NPC status before you pressing A also affect the results.
It's safe to use frame that jump from 3 frames (=npc+1) before, i.e if you see 600->603, then 603 is a predictable frame. But it's wield to me and needs more tests.

**Comment by Real96** [comment]
So, you have just to set the encounter to 50 rate to predict the nature?

**Comment by wwwwwwzx** [comment]
For stationary, I already included button pressing delay into the `Time Delay` or the program, so you don't need to add more delay using PokeCalcNTR. 
When there are multiple NPCs, the spread depends on not only the timing you press A but also the history.. So if you only focus on which frame you are at, the spread can always be unpredictable in some sense.
Maybe I can impl some feature later..

**Comment by Real96** [comment]
The error i was talking was the one of the issue, not Solgaleo/Lunala xD

Anyway i understood, that's why the error is allways the same. Let me know if you find a way to predict it :) I'm completely free to make some tests if you need

**Comment by wwwwwwzx** [comment]
which issue?

**Comment by Real96** [comment]
The main issue xD "Tapu Fini Error when i try to search a spread #12" this one xD can't reproduce it anymore

**Comment by wwwwwwzx** [comment]
Solgaleo/Lunala/Cosmog were fixed, check it out.
Tip: The frames **without** `?` under `Blink` Column are good frames

**Comment by Real96** [comment]
Ok, i'll try them now and tell you if i can RNG them :) And for type null? Any news? I can also give you my save file with it

**Comment by wwwwwwzx** [comment]
That one I can PKHex it~ XD

**Comment by Real96** [comment]
Event flag, you're right xP Try also it if you can and let me know. I'm trying Solgaleo now

**Comment by wwwwwwzx** [comment]
As for Type:Null, I guess the only thing to do is calibrate the `Time Delay`, since Cosmog is same type Pokemon (Always Synced). But it's hard to find a "good frame", it's severely affected by the history.

**Comment by Real96** [comment]
Yes understood, i'll make some test also for it.

I just RNGed Lunala, this application is becoming really fantastic! The only thing to do is selceting Show results after delay and hit the correct frame in game.

**Comment by wwwwwwzx** [comment]
Thanks to PokeCalcNTR, so I can see how the RN flows and make a guess

**Comment by Real96** [comment]
Yes PokeCalcNTR is really great! Can you remove the frames with `?` under `Blink` Column from the results? It that way the app will show us only the good frames

**Comment by wwwwwwzx** [comment]
I tested Aerodactyl, the default value works..

**Comment by wwwwwwzx** [comment]
Sure, I'm also thinking of increasing the range of good frames.

**Comment by Real96** [comment]
Fantastic! Do the Synch showed in the results is correct for Solgaleo/Lunala? Or still got some problems?

**Comment by wwwwwwzx** [comment]
I think no.. It shouldn't be.. The only problem is you may shift to +3 frame if you pause at the later part of that frame.

**Comment by Real96** [comment]
Ok, i'll make some tests for the synch anyway. And for Magearna?

**Comment by wwwwwwzx** [comment]
NPC = 6 or 7 based on my former test.. because of a walking man. But you can stop him by starting conversation.

**Comment by Real96** [comment]
Yes but the Delay? 38 is good?

**Comment by wwwwwwzx** [comment]
Testing, I'll let you know if I find the answer

**Comment by Real96** [comment]
You're really doing a great job. I'm testing Solgaleo and Lunala. They both work perfectly! Synch and frame alway correct, the only "problem" is that the game may skip your frame due to the +3 advancement

**Comment by wwwwwwzx** [comment]
Good frame filter added

**Comment by Real96** [comment]
Great! Anyway i tryed a `?` frame for Cosmog, and i hit it. Is there a way to find which frame with `?` is good?

**Comment by Real96** [comment]
Spred i hit: http://i.imgur.com/kx9opXI.png

Screen: http://i.imgur.com/rK28B1d.png

**Comment by wwwwwwzx** [comment]
If it is advanced from -4F when you pressing select, That's the good frame.

**Comment by wwwwwwzx** [comment]
Yes That's why i am using ? not X

**Comment by Real96** [comment]
Ok, i will try all the frame then xD I'll try Magearna, let's see what happens. I think that after all of the the one missing things will be event pokemon

**Comment by Real96** [comment]
Just tryed Magearna and with  a good frame and it worked! I need to test the `?` frames

**Comment by wwwwwwzx** [comment]
Sounds good! I changed the word "good" to "safe"

**Comment by Real96** [comment]
Perfect. 
It seems that:
Safe Frames will always work with 6 NPCs and 38 Delay
`?` Frames will work if it advances 8F when you press selvect to arrives , 6 NPCs and 38 Delay

**Comment by Real96** [comment]
Type:Null worked too! Didn't test `?` frames yes but with safe frames and 8 NPCs i hit the correct frame

**Comment by wwwwwwzx** [comment]
Nice! I'm wondering if there is a definite number of NPC for Magearna. If not, it seems to me that we have to check the NPC number after getting into the conversation. I'm focusing on UB without honey case (which is hard to use), then release it.

**Comment by Real96** [comment]
I tryed with the man near me and with him out of the screen and the results where the same

**Comment by wwwwwwzx** [comment]
Just leave it. It seems encounter without honey is 100% predicted now..All done, I think I can release it

**Comment by Real96** [comment]
How do you make the encounter start on the right frame without honey?

**Comment by wwwwwwzx** [comment]
Actually no way.. so it's useless.. You have to keep moving..

**Comment by Real96** [comment]
So it is only to check the frame you got while you're in battle xD

**Comment by wwwwwwzx** [comment]
Try the `create timeline` function. Use `safe frame`  or the frame you get into the main map as `Frame Range` lower limit

**Comment by Real96** [comment]
I didn't understand what it is used for >.<

**Comment by wwwwwwzx** [comment]
100% correct results since the software is tracking the NPCs’ status, maybe helpful to RNG Type:Null.

**Comment by Real96** [comment]
I'm testing it now. Do i need to leave it as 600?

**Comment by wwwwwwzx** [comment]
You can see you are exactly following the timeline by pressing select, if there is no bug

**Comment by Real96** [comment]
I think it doesn't work. It says 4495, but i got 4492 and then 4500...the game skipper skipped 4495

**Comment by wwwwwwzx** [comment]
Needs to find `safe frame` as starting point first

**Comment by Real96** [comment]
What do you mean? I need to be on a safe frame without pressing A and then make the search with the timeline with this frame as lower Frame Range?

**Comment by wwwwwwzx** [comment]
Yes, pause at one safe frame first, then make a search.

**Comment by Real96** [comment]
God it works prefectly! This is a great things! Jus tried it now, and it follows perfectly time line!

**Comment by wwwwwwzx** [comment]
And NPC for Magearna can be 7. I leave the man nearby and tested.

**Comment by Real96** [comment]
Really? Maybe i didn't pay to much attention, so 7 with the man nearby, good to know.
Can you test events pokemon? I made some tests, in the first pokemarket you meet on the game storyline. 8 NPCs as Type:Null and 38 Delay, but sometimes i can hit the frame and sometimes i hit -1 or -5 (using only safe frame)

**Comment by wwwwwwzx** [comment]
Will test later,  I'm going to sleep now. I know Japanese Machamp's attack is fixed 31, nature is fixed brave, the rules may be different.

**Comment by Real96** [comment]
I tryed it with munchlak, nothing is fixed, neither the IVs >.< anyway it would be great for the new incoming Shiny Tapu Koko event :D Anyway good night! See you later!

**Comment by Real96** [comment]
I'm closing this issue because it is becoming too big and almost everything has been fixed xD I'm creating a new for the Events pokemon.
