### ISSUE TITLE
Disable Create Timeline for methods that aren't Gift/Solgaleo/Lunala/Events

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#15]
`Create Timeline` should be removed for methods that aren't Gifts/Events/Solgaleo/Lunala, to generate correct frames

**Comment by wwwwwwzx** [comment]
Do you mean the spreads are incorrect, or just don't need it

**Comment by Real96** [comment]
No, the frames change

**Comment by Real96** [comment]
Without Timeline: http://i.imgur.com/fG0EQwo.png
With Timeline: http://i.imgur.com/YBrztLg.png

**Comment by wwwwwwzx** [comment]
This function should fix all `?` frame if the starting point is correct.
The results not listed in the Timeline are unable to reach in some sense.

**Comment by Real96** [comment]
Yes but i mean with the UBs/Lele/Bulu/Koko you can reach every frame, does it change the frame also for them?

**Comment by wwwwwwzx** [comment]
Oh you remind me. for UBs, I have to clear the Status

**Comment by Real96** [comment]
UBs and also Bulu/Lele/Koko >.<

**Comment by wwwwwwzx** [comment]
Results of Bulu/Lele/Koko are almost identical. But if you pause in the blinking cool down. I guess Timeline will give the right answer. I will try when I come back home

**Comment by Real96** [comment]
Ok i think you're right. For example if 682 has got the star near, if you click Create Timeline it will show you like the next 10 frames as 683,683, 683, 684, 684 and so on. This is normal right?

**Comment by wwwwwwzx** [comment]
Yes, you can see it by pressing select, the game also stay there. And the last several rows in timeline will give unique results.

**Comment by Real96** [comment]
Perfect. So just fix it for the UBs and then you can close this issue :)

**Comment by wwwwwwzx** [comment]
Can you help me try those special spreads out? Since the frame stops, you have to track how many times select you pressed after entering that region.

**Comment by Real96** [comment]
In that case i have to count 2 select as 1, right?

**Comment by wwwwwwzx** [comment]
yep

**Comment by Real96** [comment]
Ok, i'll test it in a bit

**Comment by Real96** [comment]
Where do i have to test it? For UBs or for Gifts?

**Comment by wwwwwwzx** [comment]
Koko/Bulu/Lele, thanks. I'm just curious about if it's correct. For UBs there is no special spreads. For gift I'm coding.

**Comment by Real96** [comment]
Ok, i need to test if the select number/2 is uqual to the number of the frame in the app if i understoon correctly, right?

**Comment by wwwwwwzx** [comment]
I guess so. Ask the author of PokeCalcNTR. You can use the last column `Time` in `Advanced` mode

**Comment by Real96** [comment]
It works the same way you told me. Select Number/2 is equal to the strings of the same frame

**Comment by wwwwwwzx** [comment]
Nice! Thank you~

**Comment by Real96** [comment]
No problem at all! If you need more tests i'm here :)
