### ISSUE TITLE
Add Always Shiny option for always shiny Events

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#17]
I tried to RNG Lunar Shiny Magikarp, which is alway shiny, but there is a litte error: the app tells you that PSV and PID are different from PSV and PID of the pokemon you get. Anyway all the other stats are correct

**Comment by wwwwwwzx** [comment]
I just hide it, it also takes 1 RN and doesn't affect other spread stats

**Comment by Real96** [comment]
Ok. It wasn't so important, you're right

**Comment by wwwwwwzx** [comment]
And the fixed TID & SID for event Pokemon will give the fixed Tsv，So the psv should be fixed to that

**Comment by Real96** [comment]
Yes but there are pokemon that can be shiny. In 6th gen there were events that could softresetted to be shiny. Also the new egg events can be rnged to be shiny (you0ll need to hatch them on a matching TSV sav). And iirc also Ash Greninja can be shiny >.<

**Comment by wwwwwwzx** [comment]
Sorry, I missed {}. just fixed it
Really? which one can be shiny.

**Comment by Real96** [comment]
The new incoming eggs (Passiman, Oranguru, Turtonator...), you receive them as egg so surely they can be shiny in an other save file. In 6th gen there was a Magikarp which could be softresetted to be shiny

**Comment by Real96** [comment]
I think you made a little error, PSV are showes as Hexadecimal and not Decimal number xD

**Comment by wwwwwwzx** [comment]
I See. I looked into the wondercard file in PKhex, there are 4 types of shiny rule... complicated..

**Comment by wwwwwwzx** [comment]
fixed. Thank you

**Comment by Real96** [comment]
Fantastic! You're so fast in fixing anything!

**Comment by wwwwwwzx** [comment]
I put it back. And I also add shiny locks to Tapus, UBs, etc. It would be great if you can try those `shiny` using old version and see if the results are predicted by new version.

**Comment by Real96** [comment]
I didn't understand what i need to test xD Which shiny do i need to test?

**Comment by wwwwwwzx** [comment]
Try `Shiny Frame` for Tapu koko before v1.02, and see if my correction in last commit is correct

**Comment by Real96** [comment]
In previus version they where showed, now no. So i think the correction is correct.

But you removed also them from the Event mode >.<

**Comment by Real96** [comment]
I think this can be close
