### ISSUE TITLE
Disable Frame Range Limit Box when Create Timeline is selected

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#18]
When you select `Create Timeline`, the app uses only `Time Lenght/s` box as limit and not anymore the number you input in the second box of `Frame Range` (the limit of frames to search). Can you disable this last one when `Create Timeline` is selected? (make only the second box of `Frame Range` grey and not modifiable). Because everytime i forgot it and i try to modify `Frame Range` xD Also other people won't be confused by this

**Comment by wwwwwwzx** [comment]
I hide it and make a label. Thank you
