### ISSUE TITLE
UB Encounter not respected

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#2]
The UB encounter isn't alway respected. I hit the correct frame, but I sometimes encounter a wild Pokémon instead of the UB. Is there a way to solve this?

**Comment by wwwwwwzx** [comment]
Try different `UB Rate `or `Frame Correction`.  I will do some test later.

**Comment by Real96** [comment]
I'm using the default UB rate. For Kartana 15 for Xurkitree 15....don't know it these are wrong or not, but also if the spread should be a UB, many time it is not

**Comment by wwwwwwzx** [comment]
Which parameters set are you using now? I just calibrated the time delay for non-UB appearance at different location. But the stats spreads for UB are still messy..

**Comment by Real96** [comment]
This are my parameters: http://i.imgur.com/XOetrOt.png

For the other UB it worker, for Xurkitree no...

**Comment by Real96** [comment]
I don't know why but the issue has been closed by me D: and i don't know how. I'm opening a new one....
