### ISSUE TITLE
Ash Greninja Error at At least IV count

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#20]
I got this error when i tried to search a spread for Ash Greninja event (it has got only fixed IVs to 20/31/20/31/20/31):

Event Pokemon Setting: http://i.imgur.com/4l89tzg.png
Error: http://i.imgur.com/lSbiWo6.png

Also `At least IV count `can arrive only to 5, i think it should arrive to 6.

**Comment by wwwwwwzx** [comment]
Ash Greninja Fixed.
That's the **Random** IV=31 number (I don't know how to label it correctly... any suggestion), cause maybe there is 5ivs rule Pokemon like bank mew.
I make the 3IVs CheckBox Visible for event Pokemon again

**Comment by Real96** [comment]
Sorry i forgot that if you put 6 random IVs it is the same as all31 fixed....so sorry xP you can label it as "N. of random 3 IVs". I think is better

**Comment by Real96** [comment]
Did you removed the PSV from events?

**Comment by wwwwwwzx** [comment]
I guess it depends on TSV which is varied

**Comment by Real96** [comment]
No i mean, under the `PSV` column there are no PSV showed as before

**Comment by Real96** [comment]
I'm closing this.

**Comment by wwwwwwzx** [comment]
Does the tool work for the greninja?

**Comment by Real96** [comment]
The nature is wrong, i was opening an issue xD
