### ISSUE TITLE
In event mode Consider Time Delay works only if Your ID is selected

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#21]
In event mode `Consider Time Delay` works only if `Your ID` is selected. If you don't selct `Your ID`, `Consider Time Delay` doesn't work. I was trying this because Greninja Nature is always wrong

**Comment by wwwwwwzx** [comment]
Now the value should be 0, and `consider time delay` still calculate your button press delay (4F). I guess the pid generation is different for Ash Greninja

**Comment by Real96** [comment]
Greninja alway get +2 from the nature i want. I think is this the problem

**Comment by wwwwwwzx** [comment]
Not only the PID but also the EC.. It's really a special case. The button press time delay still work..

**Comment by Real96** [comment]
So there is no way to be fixed?

**Comment by wwwwwwzx** [comment]
I can change the checkbox to droplist.

**Comment by Real96** [comment]
don't know what it means, but i can test any modification if you need xD

**Comment by wwwwwwzx** [comment]
Check new commit. Choose `specified` for greninja

**Comment by Real96** [comment]
Fantastic now it works! Maybe you can disable consider time delay when it is not used, to avoid any confusion. Other than this there aren't any error at the moment

**Comment by wwwwwwzx** [comment]
Actually now this delay includes the button pressing delay. It's always there.
Anyway, when people use this tool, just choose the Pokemon, change the filters and Press "search".
I can disable it for all.

**Comment by Real96** [comment]
Mhmhm if it is in that way, i think is better to leave it as it is. Great job! You fixed everything (at the moment xP)

**Comment by wwwwwwzx** [comment]
To avoid confusion, I add a small label behind it. Thank you for the advice

**Comment by Real96** [comment]
Fantastic! Great job! :D You can close this issue :)
