### ISSUE TITLE
Error in Solgaleo/Lunala Predicton

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#23]
The new release is giving me an error of Solgaleo/Lunala spreads prediction. The older version had always a correct prediction. These are the screen:

My frame: http://i.imgur.com/c56CajN.png
Safe Frame: http://i.imgur.com/zZrwxaq.png i arrived to 551 in game
Target: http://i.imgur.com/F0SefqQ.png
Hit the target: http://i.imgur.com/O0KgDwM.png
Wrong Spread: http://i.imgur.com/WNWp7f2.png

I made the same search of seed/frame in a previous version and the results was the same as the new...i'm making more tests

It worked making another test with another initial seed, i think this is an isolated case. The frame was advancing +1 everytime, i think that this caused the wrong spread

**Comment by wwwwwwzx** [comment]
Yes sometimes safe frame might be unsafe.. I'm thinking of the reason. Sometimes the player move will cause the shift.

**Comment by Real96** [comment]
Do i need to test something?

**Comment by wwwwwwzx** [comment]
Try to **double** check the safe frame first, and then let it follows the timeline, and see if there is any other problems. Solgaleo/Lunala doesn't have dialogue box, something may not be frozen. Just a guess. But I also see this problem in Type:Null, that's weird.

**Comment by Real96** [comment]
Didn't have this problem with type null. I'll test it again so

**Comment by Real96** [comment]
Not OP, but why you cahnged NPCs to Models? XD

**Comment by wwwwwwzx** [comment]
Treat pokemon, player and NPC equally. XD And no more add 1, minus 1 math work. The maximum frame advance is just the number of models.

**Comment by Real96** [comment]
Damn you change everyt valueeee. Ok, i need to update my guides xD

**Comment by wwwwwwzx** [comment]
Sorry about that

**Comment by Real96** [comment]
Ahahaha no problems!

**Comment by wwwwwwzx** [comment]
That will reduce lots of misunderstanding. I should have changed that after copying quandra's code

**Comment by Real96** [comment]
I think that maybe is better if you put everything as before, because now everywhere is written that NPCs start from 0 t.t i think that this change will make more misunderstanding

**Comment by wwwwwwzx** [comment]
Reverted.

**Comment by Real96** [comment]
Thanks! I'm testing Solgaleo to check the Safe Frames

**Comment by Real96** [comment]
It seems that everytime that the character move his body, the `Timeline` is broken

**Comment by wwwwwwzx** [comment]
I guess that's it. And the animation of lunala is also strange.. The npcs number are changing

**Comment by Real96** [comment]
There was the author of pokecacl who wanted to talk with you about this on reddit. I tagged you on his comment

**Comment by wwwwwwzx** [comment]
I talked with him. Thank you

**Comment by Real96** [comment]
Perfect. Are you both trying to find the solution? XD

**Comment by wwwwwwzx** [comment]
No I already have the answer of his question.
The Japanese Lunala looks so weird. I'm trying to understand.
Do you remember what you did to make the NPC number so less

**Comment by Real96** [comment]
What do you mean? You are asking me if there was a way to reduce the number of NPCs to 2?

**Comment by wwwwwwzx** [comment]
Yes, something special?

**Comment by Real96** [comment]
I think no. I went there for the first time, i made the backup and then i cathced it....nothing so special

**Comment by Real96** [comment]
I also noticed that sometimes, on my save file, both Solgaleo and Lunala frame advances +1 for a bit and it starts normally advancing +3.

**Comment by Real96** [comment]
Did you solved also this?

**Comment by wwwwwwzx** [comment]
Yes, I only solved the half the problem, the timeline needs more time.
And does Solgaleo also have npc=6 case?

**Comment by Real96** [comment]
I'm waiting my friend testing it with Solgaleo. Lunala 6 npcs worked. Anyway if you try to put npcs 4, the program give you an error

**Comment by wwwwwwzx** [comment]
Actually in the npc=6 case, during the animation after screen turning black, two guys drops off, I didn't add any protection for npc=4. Fix soon

**Comment by Real96** [comment]
Yes, infact to find the spread in the results, i had to change the number of the NPCs

**Comment by Real96** [comment]
The NPCs error seems fixed in the last commit

**Comment by Real96** [comment]
Magearna has got the same problem as Solgaleo/Lunala :/ Sometimes the frame is skipped t.t Also sometime it follows NPCs 5, 6 o 7.....

**Comment by wwwwwwzx** [comment]
Try to start the dialogue and freeze unknown movements

**Comment by Real96** [comment]
It happens rarely. I was only testing, now it seems to be normal, but 5 minutes ago i needed to put npc 7 to make it follow the timeline

**Comment by wwwwwwzx** [comment]
I can tell you how I determine npcs. Use honey at that location, see the 2nd/3rd frame advance, then -1.
ps: the 1st frame advance will be the honey correction we're gonna test.

**Comment by Real96** [comment]
Yes, i will use this method

**Comment by wwwwwwzx** [comment]
https://github.com/wwwwwwzx/3DSRNGTool/commit/b7b49fa5020ec92afb0d5a6f11146189de931788
