### ISSUE TITLE
Modify Frame and Time columns lenght

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#24]
Add the possibility to modify the Time and Frame column lenght, because the frame and the time sometimes are too long to be fully displayed

**Comment by wwwwwwzx** [comment]
How many digits do you have?

**Comment by Real96** [comment]
8. Really common for Type:Null xD

**Comment by wwwwwwzx** [comment]
That's half a day. XD Fixed

**Comment by Real96** [comment]
Don't you know that i'm crazy? XD Thanks!
