### ISSUE TITLE
Solgaleo/Lunala 5-6 NPCs

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#26]
A friend is trying to RNG Lunala, but the frame acts like NPCs 5 and sometimes also 6 (with the last commit version) and when he try to hit a frame, the spread is different from the app.  He passed me his save file, and i got the same error. I know also another freind who have this same problem with Solgaleo. Can i send you the save file? So you can check it

**Comment by wwwwwwzx** [comment]
Sure~ I also heard from someone who said npc = 6

**Comment by Real96** [comment]
Sent. Tell me if you received it. Let me know if you can figured out :)

**Comment by wwwwwwzx** [comment]
I guess I figured out....

**Comment by wwwwwwzx** [comment]
I'm testing the function of github. It was closed by the command.
I tested 7 times for Lunala. It works perfectly as usual now. Please help me check if Solgaleo is also fixed.

**Comment by Real96** [comment]
Ok, i'll test both and i'll let you know :)

**Comment by Real96** [comment]
It doesn't work :/ It doesn't follow the timeline....

**Comment by Real96** [comment]
Sorry, I tested it again. I was using a wrong seed xD It works :D Thank you!

**Comment by Real96** [comment]
Also Solgaleo follows the timeline :) Great!

**Comment by wwwwwwzx** [comment]
npc=6 for solgaleo? I'm gonna change npc=6 as the default value.

**Comment by Real96** [comment]
Oook, i think that the one strage is my save file xD

**Comment by wwwwwwzx** [comment]
Maybe due to the language, CHS and JPN are 6, others are 2. Do you try other language?

**Comment by Real96** [comment]
No, because my friend solgaleo was Italian :/

**Comment by wwwwwwzx** [comment]
Yeah I recall that one japanese RNGer said that there were total 3 people blinking when catching solgaleo several weeks ago. 
You are not the only one xD

**Comment by Real96** [comment]
Ok, so i'm not the only one xD
