### ISSUE TITLE
Honey Correction in Alola

### ISSUE THREAD

**Issue by wwwwwwzx** [wwwwwwzx/SMEncounterRNGTool#27]
Massive testing required

**Comment by Real96** [comment]
Which test?

**Comment by wwwwwwzx** [comment]
Yes starts from route 1

**Comment by Real96** [comment]
This will be crazy! Ahahaha i will help you :)

**Comment by wwwwwwzx** [comment]
Just a thought, you can help me update the file [here](Event Pokemon Setting.md) first

**Comment by Real96** [comment]
Yes, i'm editing it :)

**Comment by Real96** [comment]
Events are completed ( i made a little of confusion, sorry xD )

**Comment by Real96** [comment]
The two first grass area of the Route 1 have bot got 0 NPCs. I'm searching the error

**Comment by Real96** [comment]
I finished all the Route 1. I tested the best area with less NPCs. I covered all the pokemon. But the encountersolts are wrong

**Comment by wwwwwwzx** [comment]
Oh really, there are 3 kinds of encounter slots table in route 1

**Comment by Real96** [comment]
Yes i know. But i thought that the biggest one should be respected, instead it is not. I'm prepearing all the info and uploading the images so you can see them

**Comment by wwwwwwzx** [comment]
Thanks a lot, I'm going to find some rules of Lunala's timeline

**Comment by Real96** [comment]
Fantastic. In the meanwhile i search all the errors/places for wild xD

**Comment by Real96** [comment]
Route 1 and Route 2 completed. Unfortunately all the Encounterslots are wrong...

**Comment by wwwwwwzx** [comment]
I just retested a little bit, I didn't see any divergence. which encounter table are you using

**Comment by Real96** [comment]
I saw in your blog that it was based on serebii order, is it right?

**Comment by wwwwwwzx** [comment]
Yes, after the "Toggle S.O.S. Details"

**Comment by Real96** [comment]
In route 1 and 2  didn't get the right encounters...i can make some screens

**Comment by wwwwwwzx** [comment]
Ok, thank you~ For the timeline, I can say it will be shift every 7-8 second, right after the player character finishing his/her movement. But finding the accurate timing is not simple...

**Comment by Real96** [comment]
Understood. I noticed that if you click X and open the menu the characted doesn't move. But the shift happens anyway. Why this?

**Comment by wwwwwwzx** [comment]
Even while you are giving name to the pokemon you recieved or you are looking the pokemon status, it also consumes random number occasionally around 7-8 secs, that's really common but mystery.

**Comment by Real96** [comment]
So strange...anyway i was making a mistake on the encounterslot. I didn't understan that i needed to open the Toogle Sos. But why the app maximum is 11 while on serebii they're 10?

**Comment by wwwwwwzx** [comment]
I use 1-10 for slot. 0 for flag.

**Comment by Real96** [comment]
I didn't understand if they are like 0=1, 1=2 ans so on or not. Also if i search encounterlot 10 i found it. If i disable the filter, i can't find any encounter 10

**Comment by wwwwwwzx** [comment]
No. The numbers below `slot` column and the text you input into the `Encounter Slot`  are just "1 for 1st slot, 2 for 2nd slot"  0 never appear.
For example 10 in wela volcano is kangaskhan, the 10th slot

**Comment by Real96** [comment]
Ok perfect. But i can't make it work.
App: http://i.imgur.com/DFwMcSa.png
Pokemon: http://i.imgur.com/tvWvOZu.png
Serebii; http://i.imgur.com/xS1GcHg.png

**Comment by wwwwwwzx** [comment]
The level is also incorrect. I guess you have the shiny charm

**Comment by Real96** [comment]
God, the damned shiny charm. You're right now they all work. Finished Route 3

**Comment by wwwwwwzx** [comment]
You can RNG all shiny Pokemon appears in each encounter slot while sweeping every route~

**Comment by Real96** [comment]
I think you locked the shiny spreads also for wild t.t because i can't find any shiny spread t.t

**Comment by wwwwwwzx** [comment]
I fixed that stupid mistake...

**Comment by Real96** [comment]
Perfect! Now i can continue studying the errors happily, hunting shiny pokemon ahahah When i finish the first island i'll make a complete comments with all the errors and the location of it

**Comment by wwwwwwzx** [comment]
Great! Thank you in advance~

**Comment by Real96** [comment]
Thank you for this app :D

**Comment by wwwwwwzx** [comment]
I finished Poni Island, would you like to help me complete the data [here] (https://github.com/wwwwwwzx/SMEncounterRNGTool/blob/master/parameters/Pre-Honey%20Correction.md)

**Comment by wwwwwwzx** [comment]
Ula'Ula Island completed

**Comment by Real96** [comment]
Also Mele Mele. But i think you have also to put the spot of any location. I made all the svreenshot of every spot

**Comment by wwwwwwzx** [comment]
The correction seems to not change in one area.

**Comment by Real96** [comment]
In MeleMele Island the correction changeinstead t.t

**Comment by Real96** [comment]
[This](http://pokerng.forumcommunity.net/?t=59613020) is what i'm doing fro the encounter. Also i'm writing you an email, check it pls

**Comment by wwwwwwzx** [comment]
Great! Thank you. I'm working on fishing RNG now.

**Comment by Real96** [comment]
Perfect! I'm going to write all the first islad locations and i start with the second after it

**Comment by wwwwwwzx** [comment]
fishing is very unstable, the time delay depends on the player's gesture when pressing A.

**Comment by Real96** [comment]
I thought it was a bit difficult xD

**Comment by wwwwwwzx** [comment]
I found some mistakes in your summery, you need to subtract 2 first for the shiny charm, and the time delay of entering bag is 12F, so you need to subtract 6*(npc+1), which may differ near blink frames, then every route has a unified constant. Like 15 in route 1, 21 in route 2, that's my definition.

**Comment by Real96** [comment]
Yes i know about the 12 if there are 2 NPCs. I didn't understand about substracting 2

**Comment by wwwwwwzx** [comment]
Great, thanks

**Comment by Real96** [comment]
You forgot the cemetery xD

**Comment by wwwwwwzx** [comment]
for route 17 check my last commits. Make sure you are following the timeline. since normally the frame advance will be 1,3,1,3,1,3 or 4,6,4,6,4,6 periodically in the safe frames zone.

**Comment by Real96** [comment]
Ok it works! But there is a little bug. When i create the timeline the app don't know after my starting frame range there is an advancement of +1 or +3. Is there a way to solve this?

**Comment by wwwwwwzx** [comment]
the tool is always create a timeline start with +3, user must tell it which timeline he/she is on

**Comment by wwwwwwzx** [comment]
But since it just affects how much correction to get into the bag, it's just 12 frame off no matter which timeline you are following. the honey part is 100% predictable.

**Comment by Real96** [comment]
So it is always +3? Perfect

**Comment by wwwwwwzx** [comment]
in tool it always +3 for the first advancement.

**Comment by Real96** [comment]
Perfect. I'm changing all correction values in my table, in that way will be the same of the program :)

**Comment by Real96** [comment]
Does this work with the UB? because the spreads don't seem to shift

**Comment by wwwwwwzx** [comment]
it should work but need to test the Ub rate. memory hill is needed to.

**Comment by Real96** [comment]
I'm testing it now. THe spreads shift, i made an error before xD

**Comment by Real96** [comment]
It works also with UBs

**Comment by wwwwwwzx** [comment]
you mean route17? perfect. let me know if you have the ub rate

**Comment by Real96** [comment]
I tested Route 17 today and itworked :) i didn't know i started always with +3. I mean the UBs :)
