### ISSUE TITLE
Tiny Issue - Reset Button resets the level to 0

### ISSUE THREAD

**Issue by SonicBlader** [wwwwwwzx/SMEncounterRNGTool#31]
Hello!

When a pokemon is selected, example Tapu Koko & some random data (IVs, etc) is input in the filters part of the program. After pressing reset, the level also gets reset to 0 while the Pokemon selected remains Tapu Koko. Is this intentional?

**Comment by wwwwwwzx** [comment]
Well it's intentional for wild Pokemon, I will remove this function for stationary pokemon. Thank you for pointing out.

**Comment by SonicBlader** [comment]
Ah great! Thank you!

**Comment by wwwwwwzx** [comment]
You can use normally. The Lv filter won't work when it is set as 0.
And it will be kept if you're `using stats` for searching method.
