### ISSUE TITLE
Crabrawler RNG Support

### ISSUE THREAD

**Issue by wwwwwwzx** [wwwwwwzx/SMEncounterRNGTool#34]
Although we can use blank stationary pokemon with` timedelay = 0`+4F and check off 3IVs, it should belong to wild Pokemon type

**Comment by Real96** [comment]
Tried in Route 3, there is a little problem with the NPCs

**Comment by wwwwwwzx** [comment]
I'm testing on route 8

**Comment by Real96** [comment]
is there a problem of NPCs changing also there?

**Comment by wwwwwwzx** [comment]
I think no.
