### ISSUE TITLE
IndexOutOfRangeException for Tapu Koko

### ISSUE THREAD

**Issue by SonicBlader** [wwwwwwzx/SMEncounterRNGTool#36]
Hello!

I was following Real96's guide on how to RNG Tapus. I was going to RNG Tapu Koko. I was able to do the initial search and I got a frame which I could set as the starting point for the timeline. I selected all the appropriate options as per the guide and mentioned the required IV spread. I clicked search and I got the IndexOutOfRangeException. 

Crash log - http://pastebin.com/idwFdnRi

Screenshots - http://imgur.com/a/EGhDO

You can see my selected options and configuration in the screenshots. Thanks!

**Comment by wwwwwwzx** [comment]
Thank you. It was fixed. Since you are using a frame during blinking cooldown and it's a `blink frame` not a `safe frame` actually. The timeline feature is not designed for npc=0 case,
