### ISSUE TITLE
Error in Route 6 and Route 7 Correction

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#37]
I just completed 1st Island and 2nd Island with all the spots photos. I was checking if all my values were the same as yours, and they are all equal. But there are only two values that are different: Route 6 and Route 7.
Both yours are correction 9, while mine are both correction 11 (11+18= 29). Can you check them again pls?

**Comment by wwwwwwzx** [comment]
Yes you are right

**Comment by Real96** [comment]
Perfect! :)

**Comment by Real96** [comment]
Also, i tested Hano Beach and your values are ok :)
