### ISSUE TITLE
SOS Pokémon Rng

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#38]
Now that pokeCalcNTR supports SOS pokemon, its RNG can be studied. Start+Left and then Start+L/R during the battle xP

**Comment by wwwwwwzx** [comment]
Hi can you use "real-time save" of NTR, I'm testing on a O3DS so it doesn't work, I'm wondering if the perfect ivs are fixed before you're using Adrenaline Orb.  Just try to save before you use Adrenaline Orb in SOS battle and see whether the perfect ivs spread change. Thank you!

**Comment by Real96** [comment]
I can test it, i've got the N3DSXL but i think it doesn't work...

**Comment by Real96** [comment]
Ad expected it doesn't work :/ it freezes my 3ds

**Comment by wwwwwwzx** [comment]
Oh okay, thanks
sos pokemon rng is really inconsistent like fishing...
I just figured out the chances of shiny

**Comment by Real96** [comment]
Damn t.t in the meanwhile i'm finishing the islands spots xD

**Comment by wwwwwwzx** [comment]
Great, I will check the value after you finishing.
The sos rng for shiny is kind of stable but I don't know how the game determine the perfect ivs spread.
I'm curious since I've never seen 5 perfect ivs ditto (4V2U is my best), that's really weird.

**Comment by Real96** [comment]
Damn. The Ivs are pretty important, Shiny Ditto 6IVs HA t.t

**Comment by Real96** [comment]
Ditto with his Hidden Ability (Imposter) copies all the IVs of your pokemon exept the HP. So we just need shininess and hidden ability prediction. Did you make both work?

**Comment by wwwwwwzx** [comment]
Only shininess prediction works. The hidden ability determination seems to be from elsewhere

**Comment by Real96** [comment]
Mh understood. Can you explain more or less how it works? I would like to test the shininess

**Comment by wwwwwwzx** [comment]
When the chain length >31 there will be 15 consecutive shiny frames, it's easy to hit and the spreads are the same.

**Comment by Real96** [comment]
So i have to make opponent pokemon call help during this 15 frames, right? Of the Frame we always use

**Comment by wwwwwwzx** [comment]
I've chained hundreds of ditto and I've never seen 5ivs ditto.. Very strange..

**Comment by Real96** [comment]
Did your pokemon has 6ivs?

**Comment by wwwwwwzx** [comment]
I never use 6ivs ditto, I use 6ivs male Pokemon from each egg groups.

**Comment by Real96** [comment]
Yes, but Imposter should copy your ivs XD that's why i'm asking you this

**Comment by wwwwwwzx** [comment]
I have substitute, helper's ability never works

**Comment by Real96** [comment]
Yes, but sometimes it should have his Hidden Ability. And with the HA, it will copy your IVs exept the PS

**Comment by wwwwwwzx** [comment]
It directly copy your stats not ivs I think

**Comment by wwwwwwzx** [comment]
I just finished 256 sos chaining encounters, I guess I have enough data for analysis now

**Comment by Real96** [comment]
Someone on resdit wrote me this....still need to test. Anyway to find the shiny spread, do i have to make opponent pokemon call help during this 15 frames, right?

**Comment by wwwwwwzx** [comment]
Yes, use Adrenaline Orb around 10-20 frames in advance, based on my experience.

**Comment by Real96** [comment]
I'll make some tests later

**Comment by Real96** [comment]
Do i need to consider the 312 frames error?

**Comment by Real96** [comment]
SOS Rng is pretty difficult xD Anyway if you want to check opponent pokemon and theyr items (cause at the moment pokeCalcNTR doesn't show them) you can use [this](http://gbatemp.net/threads/pkmn-ntr-real-time-memory-editing-program-for-pok%C3%A9mon-games-wip.448588/)

**Comment by wwwwwwzx** [comment]
done
