### ISSUE TITLE
Xurkitree and Necrozma UB encounters aren't respected

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#4]
These are my parameters: http://i.imgur.com/XOetrOt.png for Xurkitree. I use UB rate 5 for Necrozma instead

For the other UB it worked, for Xurkitree no...rarely i encounter it, but most of the time i eoncouter a Wild. Under "UB?" there is the O so I should encounter it....

**Comment by wwwwwwzx** [comment]
Try `TimeDelay = 186` , `Frame Correction = 10` and subtract 14 frames to your "pre-timer" in your method. In the lastest version (0.80b and above), just set the `Honey Correction` according to README.md. Hope that helps.

**Comment by srwgin** [comment]
when you push A on bag
some times take 7F some times take 6F
is it normal
and you said subtract 7 frames it is this time right？

**Comment by wwwwwwzx** [comment]
I know that, actually my starting point is the frame where you are already in the bag menu. The key point is the honey animation time should be 186F and add 3 more Fs to "pretimer", Now the UB appearance results should be right. (I try hundreds of times for non-UB Pokemon)
Since I add 10 more frames as blinking process(for the most case it's true) between UB/Sync determination and IVs/Nature determination. You needs subtract 10 from honey delay.
So 3-10 =-7

**Comment by wwwwwwzx** [comment]
To avoid confusion, you can try to manually advance the game by 1/30s after pressing A on "Use this item". You can see some certain number of frame advances ( for example 26Fs in Malie Garden which means the `Honey Correction` in my tool) before the honey animation begins.

**Comment by srwgin** [comment]
ok but git only has 078b bandupan 079a
where is 080

**Comment by wwwwwwzx** [comment]
Needs more tests with UB.

**Comment by srwgin** [comment]
is it possible support multiple choice for encounter slot
for example
if I want rng a wild Salandit in Wela Volcano Park I can choose 1 3
if I want rng a wild Cubone in Wela Volcano Park I can choose 5 6 9

**Comment by Real96** [comment]
The Delay for all the UBs i always sue is 192, not 186. The only UBs that doesn't work are Necrozma and Xurkitre....all the other work eith this parameters. I'll try the last commit and i'll make you know

**Comment by Real96** [comment]
I MADE IT WORKS! This app is awsome! Thanks a lot for this. I made an error, i was not considering its error of 10. Now i made it works! I'm clising this issue :)

**Comment by wwwwwwzx** [comment]
@srwgin I changed the droplist to textbox. Now you can input the encounter slot yourself. Separator can be comma or space.
PS: Please open a new issue next time.
