### ISSUE TITLE
Multiple Natures Selection for Events Pokémon

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#41]
It would be great if we could choose more than one nature while searching event pokemon spreads (events without fixed nature) :) Because synchronizer doesn't work and we have to switch them everytime to search more nature spreads

**Comment by wwwwwwzx** [comment]
No build-in multiple selection control in C#, you can open two apps... Too lazy to customize

**Comment by Real96** [comment]
Ahahah ok, then just close this issue xD

**Comment by Admiral-Fish** [comment]
What do you think about using rng reporters custom dropdowns? Let's you select multiple natures at a time.

**Comment by SonicBlader** [comment]
This will useful for the Hidden Powers also. We can select the required multiple Hidden Powers we want to search for!
