### ISSUE TITLE
Wild Pokemon wrong gender in spreads

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#42]
The gender of wild pokemon spreads sometimes is wrong

You can see it [here](http://i.imgur.com/JBpHBVS.png)

[Here](http://i.imgur.com/T8RAG5X.png) instead there is the wrong gender and wrong encounter slot. These are the encoutner slots i get in  this specific spot:
1 Trumbeak
2 Mudsdale
3 Fearow
4 Fearow
5 Cottonee
6 Tauros
7 Miltank
8 Cottonee
9 Cottonee
10 Cottonee

I can't bettle Gumshoos/Raticate using honey. Standard walking instead yes. Pls check it and let me know!

I'm in Poni Plains

P.S. I've almost finished the Correction/NPCs table values!

**Comment by wwwwwwzx** [comment]
make sure you are at the correct grass area and not using cute charm ability as party leader.

**Comment by Real96** [comment]
I've not got cute charm ability. As i told you i can encounter Gumshoos/Raticate only walking but notì when  i use honey. I'm in the spot of Mudsdale, it happens only there...

**Comment by wwwwwwzx** [comment]
I am busy these days. I will try when I have time

**Comment by Real96** [comment]
Ok, let me know!

**Comment by wwwwwwzx** [comment]
According to [here] (https://pastebin.com/ih5SMYe0) and what you said, the first slot should break into two halfs, the first half is for Raticate/Gumshoos, the second half will be trumbeak

**Comment by wwwwwwzx** [comment]
Try the last commits

**Comment by Real96** [comment]
It works! :D Did you also figured out the gender error?

**Comment by wwwwwwzx** [comment]
Should be fixed in https://github.com/wwwwwwzx/SMEncounterRNGTool/commit/9397eebaac7b8fcc2cd3e6a881f3a664505084cb

**Comment by Real96** [comment]
This is for gender or for nature?

**Comment by wwwwwwzx** [comment]
Actually it's fixing gender. Nature is before gender, the problem is wild pokemon, unlike stationary pokemon, will also use another random number for nature even it has been synchronized.

**Comment by wwwwwwzx** [comment]
You can double check under this condition: the frame with sync? = "O" and when this two version give different gender prediction.

**Comment by wwwwwwzx** [comment]
I found my thoughts was incorrect, do you use synchronize as a leader?

**Comment by Real96** [comment]
No, i don't. What happened?

**Comment by wwwwwwzx** [comment]
Well, it's just the party leader issue, the default setting before is assuming you always have a synchronize party leader.

**Comment by Real96** [comment]
Did you solved it anyway?

**Comment by wwwwwwzx** [comment]
solved. just try with different party leader to check if it's correct

**Comment by Real96** [comment]
Do you mean that when there is the "O", if my leader hasn't got the synch, gender can be different?

**Comment by wwwwwwzx** [comment]
Yes, that's it. It still needs random number for nature, and gender will be the next.

**Comment by Real96** [comment]
Perfect. I'll continue making tests with Synch leader then :)

P.S I love `Wild Encounter Setting` and `EnterBag Time` option! I need now to change all value in my table xD

**Comment by Real96** [comment]
Does with `EnterBag Time` option aloow us to find correct spread also without considering 6 x (# of NPCs + 1)?

**Comment by wwwwwwzx** [comment]
Yes, it's just doing that. (it will be correct even when each frames advancement step is not NPCs +1)

**Comment by Real96** [comment]
That's fantastic! Anyway i finished the table, the only missing thing is Route 17. How can i test it? The frame advance +3 and then +1 everytime.

**Comment by wwwwwwzx** [comment]
That's a really strange place. The frames flow in a different way. Have to modify the whole time calculation system.

**Comment by Real96** [comment]
I'm going to test all the spots again from the beginning and see if all the value you put are correct! In that way i can also look at the naure/gender. Let me know for route 17

**Comment by wwwwwwzx** [comment]
Thanks a lot. I manually input all slots info so there should be lots of mistake.

**Comment by wwwwwwzx** [comment]
I'm closing this
