### ISSUE TITLE
Need more info on finding seed

### ISSUE THREAD

**Issue by MSBCOOL** [wwwwwwzx/SMEncounterRNGTool#44]
How do you use the clock hands to find the seed? I see that there are clock faces in the toolbox. How many times do I check the clock in the trainer card? Do I need to check the beginning point or the end one?

**Comment by MSBCOOL** [comment]
PS If I'm hunting for a genderless wild Pokémon, what gender do I put in?

**Comment by wwwwwwzx** [comment]
8-10 times until there is only one result. I recommend looking at ending point. For gendless wild Pokemon set genderratio to “-”

**Comment by MSBCOOL** [comment]
Thank you so much for the quick response!
