### ISSUE TITLE
Safe F Only doesn't work if you select Modification

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#45]
When you select `Modification`, the `Safe F Only` option doesn't work. Look here:

[With `Modification` actived](http://i.imgur.com/yvWd6h0.png)
[Without `Modification` actived](http://i.imgur.com/BGM355M.png)

Is `Modification` used for creating a timeline with also unsafe frames? If yes, i think is better set it unselected as default

**Comment by wwwwwwzx** [comment]
Modification mode is targeting eontimer/emtimer users.

**Comment by Real96** [comment]
Great! :)
