### ISSUE TITLE
Add Time Delay for non-UBs Pokémon

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#5]
Can you add Time Delay (as [this](http://i.imgur.com/Sc8uHaU.png)) for all the other pokemon that are not UBs, with multiple NPCs? Like for Solgale/Lunala, Cosmog....it was really useful to find the right frame to hit with the animation delay. For example i succesfully RNGed Solgaleo with Time Delay 300 + 2 NPCs, Lunala with 294 + 2 NPCs, Cosmog with 8 + 3 NPCs. It was implemented in 0.79beta, i used it selcting Honey, but now it has been changed with different numbers for UBs so it's impossible to be used with the other pokemon

**Comment by wwwwwwzx** [comment]
Sure. Thank you for your advice! I will put that back

**Comment by Real96** [comment]
Great, thanks a lot!

**Comment by wwwwwwzx** [comment]
See the lastest commit

**Comment by Real96** [comment]
There is a bug, if you change 186 o another number, it does always the calculation with 186

**Comment by wwwwwwzx** [comment]
Now should be Fixed. Sorry for the confusion

**Comment by Real96** [comment]
Now it works perfectly! 
Not a request, but maybe the only thing that still need to be changed is the line "Use Honey at" with something like "Hit frame...", not so important but only wanted to say it xD

**Comment by wwwwwwzx** [comment]
Yeah I just corrected that XD

**Comment by Real96** [comment]
Perfect. Wait still one thing to be fixed: remove Consider Time Delay from the UBs. They only need the Correction box

**Comment by wwwwwwzx** [comment]
Now, they will be disabled when `honey` is checked. I'm gonna look into UB generation. Looking forward to your data points about stationary Pokemon.

**Comment by Real96** [comment]
I'll make some test and tell you what i will find! Anyway now "Use Honey at", in UBs, has been removed xD

I tesed all of the UBs today and 186 fixed is perfect :) also all the value you provided in the main page are great, they all works

**Comment by Real96** [comment]
First two attemp with Guzzlord and synch as my party leader

1) Tryed a synch spread, and i got the synched Guzzlord
2) Tryed not synched spread and i got a not synched Guzzlord but with the wrong nature from the spread. The app says Hasty, but the Guzzlord i got was Brave (my synch is Modest)

**Comment by wwwwwwzx** [comment]
Show me the seed and spread

**Comment by Real96** [comment]
[Here](http://i.imgur.com/nHUhvsZ.png)

**Comment by Real96** [comment]
Ok i found the problem: there is an error in the Guzzlord value, it is not 3 but 1. With 3 i always get frame-2, with 1 i always get the right frame. And the natures are all right

**Comment by wwwwwwzx** [comment]
Yes you are right. It depends on specific spots. Just minus 14 from your original data [here](http://pokerng.forumcommunity.net/?t=59574488#entry423118019).

**Comment by Real96** [comment]
That guy is me xDI made this guide based on the Quandra app. Now i'll update it with your tool and all the new frame corrections :)

**Comment by wwwwwwzx** [comment]
I knew that XD. I'm closing both issue

**Comment by Real96** [comment]
Sorry, i misread xP Perfect! Anyway i found another little bug i think, i'm opening another issue
