### ISSUE TITLE
Incorrect Encounter Slots for Haina Desert

### ISSUE THREAD

**Issue by WenSnake** [wwwwwwzx/SMEncounterRNGTool#56]
Dugtrio is incorrectly listed for Encounter slots 2, 4, 7, 8, 9, and 10.

Both [Real96's Guide](http://pokerng.forumcommunity.net/?t=59613020&p=424508041) and Serebii lists Dugtrio for slots 2 and 4 only.

I only noticed when I encountered a Sandile for slot 10 in the desert.

I'm using the newest release v1.1.1

Edit: Resolution Cave (B1F) lists Zubat and Diglett for both Day and Night, when it should Golbat and Dugtrio.

**Comment by wwwwwwzx** [comment]
Fixed. thanks
