### ISSUE TITLE
[Feature Request]Pokemon Filters Presets

### ISSUE THREAD

**Issue by SonicBlader** [wwwwwwzx/SMEncounterRNGTool#57]
Hello!

I was thinking that it would pretty nice to have preset filters which we can create and then reuse when we require. For example, when you RNG a Shiny Tapu Koko, usually you aim for a 5IVs 0 Attack HP Ice. We can have presets to automatically enter the required IV ranges for each stat, Hidden Power, Ability(?), Gender & Nature. 

We can create or manage the Presets in the Toolkit tab and assign a name to it. We can select which preset we require from a drop down box. It can be placed next to the reset button (See 1 in image) or below the Time Calculator (See 2 in image). Below the Time Calculator would be better suited as there is ample space for it.

http://i.imgur.com/Rl98ZFo.png

I understand that this might be something not too important of a feature. But I hope that something like this will be implemented in the long term! Thank you very much for your work! :D

On the side note, Reset button doesn't reset "# of perfect IVs" field.

**Comment by wwwwwwzx** [comment]
Sorry for the late reply. this feature has been impled in new tool we are working on, thank you for the suggestion.

**Comment by wwwwwwzx** [comment]
https://github.com/wwwwwwzx/3DSRNGTool
