### ISSUE TITLE
Please change ENDPOINT of rng-api

### ISSUE THREAD

**Issue by odanado** [wwwwwwzx/SMEncounterRNGTool#58]
Hello

I'm a developer of [rng-api](https://github.com/odanado/rng-api) .
I have updated the API, please change ENDPOINT of the API as follows.
But, I didn't change the specification of the API, You can use API as usual.

# deprecated
```
http://49.212.217.137:19937/gen7/sfmt/seed
http://49.212.217.137:19937/gen7/sfmt/seed/id
https://rng-api.poyo.club/usm/sfmt/seed
https://rng-api.poyo.club/usm/sfmt/seed/id
```

# New API
```
https://rng-api.odanado.com/sm/sfmt/seed/
https://rng-api.odanado.com/sm/sfmt/seed/id
https://rng-api.odanado.com/usm/sfmt/seed/
https://rng-api.odanado.com/usm/sfmt/seed/id
```

**Comment by wwwwwwzx** [comment]
I made the changes on my both repo.
Thank you so much for providing us these awesome APIs.
