### ISSUE TITLE
App doesn't find all the UBs spread depending on the Frame Correction

### ISSUE THREAD

**Issue by Real96** [wwwwwwzx/SMEncounterRNGTool#7]
This is what i get with Frame Correction 0: http://i.imgur.com/L4SFJDu.png
And this with Frame Correction 10: http://i.imgur.com/TbluAgu.png
This happens only with UBs. I think that in both case it should show me both spreads but with different frames and not removing one of them...is it a bug? or it is a correct behaviour?

**Comment by wwwwwwzx** [comment]
Just uploaded a new commit. Check it out. You'd better check `show results after delay`.

**Comment by Real96** [comment]
Just tryed, now it shows only one spread both with 0 and 10. So I think that the other spread was not a UB spread then.

Yes, `show results after delay` is a great things for UBs! I'm going to use it always :)

**Comment by wwwwwwzx** [comment]
Well actually for now, the `Frame Correction` in `RNG Info` lost its function. If my assumption is right. I will delete this option in the later version

**Comment by Real96** [comment]
It is used only for UBs i noticed. For the other Pokémon it isn't so useful (and maybe it neither works) so i think you can fix it to 10 and completely remove it

**Comment by wwwwwwzx** [comment]
I don't know if there is any Sync issue associated with Tapus. Needs more tests and time..

**Comment by Real96** [comment]
I can make some tests, anyway sync isn't always respected for all the Pokèmon, also if the app says that the spread will respect the sync. Yesterday for example i got 2 times Gazzlord with no working synch. It works only for Cosmog, null and some other because it is 100%.

**Comment by wwwwwwzx** [comment]
In the last commit, I guess I fixed sync problem for UB. XD. If you remember your Seed just re-calculate it

**Comment by Real96** [comment]
Really? :O I didn't know this, I'm making some tests now, just wait a bit and i tell you if sync works for UBs and Tapu

**Comment by wwwwwwzx** [comment]
Tapus are not fix yet. Thank you for helping me~

**Comment by Real96** [comment]
It's a pleasure, your app is really great! Anyway, i'm trying only the UBs so
